
services:
  bot:
    build: .
    env_file:
    - .env
    volumes:
      - ./db/discordusrs.db:/app/db/discordusrs.db:rw
      - ./db/karma.db:/app/db/karma.db:rw
      - ./db/quotes.db:/app/db/quotes.db:rw